number_per_page: 5
done: "1"
level:
  level0: "0"
  level1: "1"
  level2: "2"
  level3: "3"
  level4: "4"
  level5: "5"
sql:
  user:
    team_users:
      SELECT * FROM users WHERE users.id
                    NOT IN (SELECT team_users.user_id FROM team_users);
    team_users_scope:
      users.id NOT IN (SELECT team_users.user_id
                    FROM team_users)
